language: cpp

cache: ccache

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

sudo: false

addons:
  apt:
    packages:
      - libsdl1.2-dev
      - libsdl-mixer1.2-dev
      - libsdl-image1.2-dev
      - libsdl-gfx1.2-dev
  homebrew:
    update: true
    brewfile: scripts/Brewfile.travis

env:
  - BUILD_TYPE=Release EXTRA_WARNING_FLAGS="-Wall -Wextra"

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then mkdir $TRAVIS_BUILD_DIR/dependency-prefix; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then export PKG_CONFIG_PATH=$TRAVIS_BUILD_DIR/dependency-prefix/lib/pkgconfig; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi
  - if [ $TRAVIS_OS_NAME == linux ] && [ $TRAVIS_COMPILER == clang ]; then export CCACHE_CPP2=yes; fi

install:
  - if [ $TRAVIS_OS_NAME == linux ]; then bash scripts/compile_YAML-CPP.travis; fi

before_script:
  - bash scripts/cmake_prepare_build.travis

script: make -j2

after_script:
  - ccache -s
